### ISSUE TITLE
java.io.FileNotFoundException: C:\Users\qcq0264\AppData\Local\Google\Chrome\User Data\Profile 2\Cache\data_0 (プロセスはファイルにアクセスできません。別のプロセスが使用中です。)

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/webdriverfactory4ks#6]
https://github.com/kazurayam/WebDriverFactory4ks/tree/0.3.0 を使ってChromeDriverFactoryTestRunnerを実行すると、Windowsでは下記のようなエラーが発生する。
```
03-09-2020 05:17:05 午後 test_newChromeDriverWithProfile(com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryTest)

Elapsed time: 1.141s

com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl.newChromeDriverWithProfile:169

com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl.newChromeDriverWithProfile:140

test_newChromeDriverWithProfile(com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryTest) FAILED.
Reason:
java.io.FileNotFoundException: C:\Users\qcq0264\AppData\Local\Google\Chrome\User Data\Profile 2\Cache\data_0 (プロセスはファイルにアクセスできません。別のプロセスが使用中です。)
	at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1138)
	at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1428)
	at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1426)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1389)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230)
	at org.apache.commons.io.FileUtils$copyDirectory.call(Unknown Source)
	at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl.newChromeDriverWithProfile(ChromeDriverFactoryImpl.groovy:169)
	at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl$newChromeDriverWithProfile$0.callCurrent(Unknown Source)
	at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl.newChromeDriverWithProfile(ChromeDriverFactoryImpl.groovy:140)
	at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl$newChromeDriverWithProfile.call(Unknown Source)
	at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryTest.test_newChromeDriverWithProfile(ChromeDriverFactoryTest.groovy:56)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at com.kazurayam.junit4ks.JUnitCustomKeywords$_runWithJUnitRunner_closure1.doCall(JUnitCustomKeywords.groovy:138)
	at com.kazurayam.junit4ks.JUnitCustomKeywords$_runWithJUnitRunner_closure1.doCall(JUnitCustomKeywords.groovy)
	at com.kms.katalon.core.keyword.internal.KeywordMain.runKeyword(KeywordMain.groovy:68)
	at com.kms.katalon.core.keyword.internal.KeywordMain$runKeyword.call(Unknown Source)
	at com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner(JUnitCustomKeywords.groovy:134)
	at com.kazurayam.junit4ks.JUnitCustomKeywords$runWithJUnitRunner$0.callStatic(Unknown Source)
	at com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner(JUnitCustomKeywords.groovy:215)
	at com.kazurayam.junit4ks.JUnitCustomKeywords$runWithJUnitRunner.callStatic(Unknown Source)
	at ChromeDriverFactoryTestRunner.run(ChromeDriverFactoryTestRunner:5)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:337)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:307)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:299)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:233)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1583741822075.run(TempTestCase1583741822075.groovy:23)

```
>Reason:
>java.io.FileNotFoundException: C:\Users\qcq0264\AppData\Local\Google\Chrome\User Data\Profile 2\Cache\data_0 (プロセスはファイルにアクセスできません。別のプロセスが使用中です。)

Macでは発生しない。

**Comment by kazurayam** [comment]
https://www.jpcert.or.jp/java-rules/fio00-j.html

>Java API 仕様 [API 2006] によると「ロックされた領域のコンテンツにその他のプログラムからアクセスできなくなるかどうかは、システムによって決まるため未規定である」。

>Microsoft Windows は強制的ファイルロックのメカニズムを使用しており、ロックされた領域がプロセスによってアクセスされるのを防止している。

**Comment by kazurayam** [comment]
今自宅のMacでChromeDriverFactoryTestRunnerを実行したらエラーは発生しなかった。

**Comment by kazurayam** [comment]
Wikipedea「ファイルロック」
https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%83%AD%E3%83%83%E3%82%AF

>Java
>Javaでは、ファイルの読み書き時は、Windows上では、java.io.FileInputStream は削除ロックが、java.io.FileOutputStream では、削除ロックと書き込みロックがかかる。明示的に、読み書きロックを使用するには、java.nio.channels.FileChannel の lock() メソッドを使用する。

**Comment by kazurayam** [comment]
ChromeDriverFactoryTestRunnerが C:\Users\qcq0264\AppData\Local\Google\Chrome\User Data\Profile 2\Cache\data_0 にアクセスするときjava.io.FileInputStreamが削除ロックを掛けようとするのだろう。このファイルがChromeのプロセスによってすでにロックされているならば、競合が起きてしまうだろう。

削除ロックをかけるFileInputStreamクラスを使わず別の方法でread-onlyで読む方法はないものか？
[java.nio.channels.FileChannel](http://e-class.center.yuge.ac.jp/jdk_docs/ja/api/java/nio/channels/FileChannel.html)なんてのもある。

**Comment by kazurayam** [comment]
https://www.baeldung.com/java-filechannel

>Mode ‘r' indicates that the channel is ‘open for reading' only. 

おお、あった、あった。C言語でファイルをopenするときにREAD-ONLYを指定するのと似たようなシンタックスがJavaにもあったのね。

**Comment by kazurayam** [comment]
java.nio.channels.FileChannelを使ってディレクトリAをディレクトリBに再起的にコピーするユーティリティを作ってみよう。

**Comment by kazurayam** [comment]
READONLYブランチを作り FileUtilsクラスを実装した。FileUtils#copyFile()メソッドはjava.io.RandomAccessFileをREAD-ONLYモードでopenする。これならWindows OSのロックと競合するのを回避できるんじゃいないかと期待して。

https://github.com/kazurayam/WebDriverFactory4ks/blob/READONLY/Keywords/com/kazurayam/ks/webdriverfactory/utils/FileUtils.groovy

ChromeDriverFactoryImplクラスを修正し、FileUtils#copyReadOnlyDirectory(File source, File target)メソッドをつかうようにした。

https://github.com/kazurayam/WebDriverFactory4ks/blob/READONLY/Keywords/com/kazurayam/ks/webdriverfactory/chrome/ChromeDriverFactoryImpl.groovy


で、ChromeDriverFactoryTestRunner　を実行した。
```
2020-03-10 13:31:49.614 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/test/com.kazurayam.ks.webdriverfactory.chrome/ChromeDriverFactoryTestRunner FAILED.
Reason:
com.kms.katalon.core.exception.StepFailedException: These following reason:
 [
	java.io.FileNotFoundException: C:\Users\qcq0264\AppData\Local\Google\Chrome\User Data\Default\Cache\data_0 (プロセスはファイルにアクセスできません。別のプロセスが使用中です。)
		at com.kazurayam.ks.webdriverfactory.utils.FileUtils.copyReadOnlyFile(FileUtils.groovy:47)
		at com.kazurayam.ks.webdriverfactory.utils.FileUtils$copyReadOnlyFile$1.call(Unknown Source)
		at com.kazurayam.ks.webdriverfactory.utils.FileUtils$1.visitFile(FileUtils.groovy:123)
		at com.kazurayam.ks.webdriverfactory.utils.FileUtils$1.visitFile(FileUtils.groovy)
		at java_nio_file_Files$walkFileTree$1.call(Unknown Source)
		at com.kazurayam.ks.webdriverfactory.utils.FileUtils.copyReadOnlyDirectory(FileUtils.groovy:99)
		at com.kazurayam.ks.webdriverfactory.utils.FileUtils$copyReadOnlyDirectory$0.callStatic(Unknown Source)
		at com.kazurayam.ks.webdriverfactory.utils.FileUtils.copyReadOnlyDirectory(FileUtils.groovy:63)
		at com.kazurayam.ks.webdriverfactory.utils.FileUtils.copyReadOnlyDirectory(FileUtils.groovy)
		at com.kazurayam.ks.webdriverfactory.utils.FileUtils$copyReadOnlyDirectory.call(Unknown Source)
		at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl.newChromeDriverWithProfile(ChromeDriverFactoryImpl.groovy:170)
		at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl$newChromeDriverWithProfile$0.callCurrent(Unknown Source)
		at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl.newChromeDriverWithProfileDirectory(ChromeDriverFactoryImpl.groovy:240)
		at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl$newChromeDriverWithProfileDirectory$6.callCurrent(Unknown Source)
		at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl.newChromeDriverWithProfileDirectory(ChromeDriverFactoryImpl.groovy:228)
		at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryImpl$newChromeDriverWithProfileDirectory$5.call(Unknown Source)
		at com.kazurayam.ks.webdriverfactory.chrome.ChromeDriverFactoryTest.test_newChromeDriverWithProfileDirectory(ChromeDriverFactoryTest.groovy:77)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.junit.runners.Suite.runChild(Suite.java:128)
		at org.junit.runners.Suite.runChild(Suite.java:27)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
		at com.kazurayam.junit4ks.JUnitCustomKeywords$_runWithJUnitRunner_closure1.doCall(JUnitCustomKeywords.groovy:138)
		at com.kazurayam.junit4ks.JUnitCustomKeywords$_runWithJUnitRunner_closure1.doCall(JUnitCustomKeywords.groovy)
		at com.kms.katalon.core.keyword.internal.KeywordMain.runKeyword(KeywordMain.groovy:68)
		at com.kms.katalon.core.keyword.internal.KeywordMain$runKeyword.call(Unknown Source)
		at com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner(JUnitCustomKeywords.groovy:134)
		at com.kazurayam.junit4ks.JUnitCustomKeywords$runWithJUnitRunner$0.callStatic(Unknown Source)
		at com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner(JUnitCustomKeywords.groovy:215)
		at com.kazurayam.junit4ks.JUnitCustomKeywords$runWithJUnitRunner.callStatic(Unknown Source)
		at ChromeDriverFactoryTestRunner.run(ChromeDriverFactoryTestRunner:5)
		at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
		at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
		at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:337)
		at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:328)
		at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:307)
		at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:299)
		at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:233)
		at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
		at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
		at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
		at TempTestCase1583814648025.run(TempTestCase1583814648025.groovy:23)
	]
	at com.kms.katalon.core.keyword.internal.KeywordMain.stepFailed(KeywordMain.groovy:50)
	at com.kms.katalon.core.keyword.internal.KeywordMain.stepFailed(KeywordMain.groovy)
	at com.kms.katalon.core.keyword.internal.KeywordMain.stepFailed(KeywordMain.groovy:23)
	at com.kms.katalon.core.keyword.internal.KeywordMain$stepFailed$0.call(Unknown Source)
	at com.kazurayam.junit4ks.JUnitCustomKeywords$_runWithJUnitRunner_closure1.doCall(JUnitCustomKeywords.groovy:150)
	at com.kazurayam.junit4ks.JUnitCustomKeywords$_runWithJUnitRunner_closure1.doCall(JUnitCustomKeywords.groovy)
	at com.kms.katalon.core.keyword.internal.KeywordMain.runKeyword(KeywordMain.groovy:68)
	at com.kms.katalon.core.keyword.internal.KeywordMain$runKeyword.call(Unknown Source)
	at com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner(JUnitCustomKeywords.groovy:134)
	at com.kazurayam.junit4ks.JUnitCustomKeywords$runWithJUnitRunner$0.callStatic(Unknown Source)
	at com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner(JUnitCustomKeywords.groovy:215)
	at com.kazurayam.junit4ks.JUnitCustomKeywords$runWithJUnitRunner.callStatic(Unknown Source)
	at ChromeDriverFactoryTestRunner.run(ChromeDriverFactoryTestRunner:5)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:337)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:307)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:299)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:233)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1583814648025.run(TempTestCase1583814648025.groovy:23)
```
残念。やはりエラーが発生しました。

**Comment by kazurayam** [comment]
僕は Chromeプロセスがどういう単位でlockするのだろうか？僕は根拠なく期待していた、
User Data フォルダより一階層下の
C:\Users\qcq0264\AppData\Local\Google\Chrome\User Data\Profile 1
C:\Users\qcq0264\AppData\Local\Google\Chrome\User Data\Profile 2
の単位でlockが行われるのではないかと。もしそうであれば手動で起動したChromeがProfile 1を使っている最中でもSeleniumがProfile 2を使ってChromeを起動できるだろう、と推測した。

ところがわたしの期待はハズレた。手動で起動したChromeが
C:\Users\qcq0264\AppData\Local\Google\Chrome\User Data
フォルダとその下にあるファイル・フォルダ全てをlockしてしまうと考えるべきだ。

**Comment by kazurayam** [comment]
ならば C:\Users\qcq0264\AppData\Local\Google\Chrome\User Data\Profile 2 フォルダの中身を別の場所たとえば C:\Users\qcq0264\Temp User Data\Profile 2にコピって、これをchromedriver起動時のオプションで指定すればどうだろうか？

という考えを2ヶ月ぐらい前に試したはず。その時何をしたか、結果どうだったかの記録が無い。ちょっとショックだったんだよね。

Profile 2を別のフォルダにコピってChromeを起動することはできた。起動することはできた。しかし期待外れだった。元のProfile 2の中のどこかにあるCookieの情報がTempのフォルダにコピーされるだろう、だからSeleniumが起動したChromeで元のCookieと同じ情報を参照できるだろうと期待した。しかし、Cookieは引き継がれなかった。

多分、Cookieの情報がファイルに記録されたときに絶対パスをどこかに保存している。そしてファイルからCookieの情報を読み取ったときにファイルに保存されたパスと現在のパスを見比べ検査する。一致すればよし、Cookieを参照して良い。もし不一致ならば異常事態、セキュリティが犯された可能性あり、だからCookieを参照できなくする。。。。というような動作をChromeがしているんじゃなかろうか。Chromeが高度にセキュリティを重じているので、テストがCookie情報を流用することをおいそれとは許してくれない、みたい。

**Comment by kazurayam** [comment]
Profile 2のフォルダをtempにコピーしてからChromeを起動しHTTPサーバと1回目のHTTPセッションしたとする。HTTPサーバが"timestamp"という名前のCookieを送ってきたとしよう。するとChromeはそのCookieをどこに保存するか。tempディレクトリに保存しますね。本来のuser-dataディレクトリではなく。

続けて同じことをもう一度やってHTTPサーバと2回目のHTTPセッションをしたとしよう。1回目のCookieは本来のuser-dataディレクトリには保存されていなくて、tempだから消えてしまった。だから2回目のセッションでChromeあからHTTPサーバに送信されたHTTPリクエストの中にはtimestamp Cookieは無い。

こういう事情であった。

**Comment by kazurayam** [comment]
Profileディレクトリをtempにコピーしてそれを参照してChromeを立ち上げるか、それとも本来のProfileディレクトリを参照してChromeを立ち上げるか、どちらかを選択して、どちらも可能にするとしよう。
